version: '3.7'
services:
  goapp:
    build: .
    image: goapp:latest
    expose:
     - "8080"
    networks: 
      - goapp
      - redis
  redis:
    image: "redis:5.0"
    networks: 
      - redis
  nginx:
    image: nginx:1.17
    container_name: production_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks: 
      - goapp
networks: 
  goapp:
  redis: