version: '3.7'
services:
  goapp:
    build: .
    image: goapp:latest
    container_name: app
    restart: always
    expose:
      - 8080
    networks: 
      - goapp-net
      - cache-net
    depends_on:
      - redis
  redis:
    image: redis:5.0
    container_name: cache
    restart: always
    networks: 
      - cache-net
  nginx:
    image: nginx:1.17
    container_name: server
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks: 
      - goapp-net
networks: 
  goapp-net:
    name: goapp-net
  cache-net:
    name: cache-net