version: '3.7'
services:
  goapp:
    build: .
    image: goapp:latest
    container_name: app
    expose:
      - 8080
    networks: 
      - goapp
      - redis
  redis:
    image: redis:5.0
    container_name: cache
    networks: 
      - redis
  nginx:
    image: nginx:1.17
    container_name: server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks: 
      - goapp
networks: 
  goapp:
  redis: